/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminLoginRequest { 'username' : string, 'password' : string }
export type AdminLoginResponse = { 'ok' : boolean } |
  { 'error' : string };
export type DownloadResponse = {
    'ok' : {
      'originalFileName' : string,
      'data' : ExternalBlob,
      'fileName' : string,
      'fileType' : string,
    }
  } |
  { 'forbidden' : string } |
  { 'notFound' : string };
export interface ExistingSubmission {
  'id' : bigint,
  'studentId' : string,
  'assessment' : string,
  'mediaType' : MediaType,
  'course' : string,
}
export type ExternalBlob = Uint8Array;
export type MediaType = { 'audio' : null } |
  { 'video' : null };
export interface Submission {
  'id' : bigint,
  'media' : ExternalBlob,
  'studentId' : string,
  'assessment' : string,
  'submittedBy' : [] | [Principal],
  'mediaType' : MediaType,
  'course' : string,
  'submittedAtUtc' : Time,
}
export type Time = bigint;
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminCreateSubmission' : ActorMethod<
    [string, string, string, ExternalBlob, MediaType],
    undefined
  >,
  'adminDeleteSubmissionById' : ActorMethod<[bigint], undefined>,
  'adminDeleteSubmissionByStudentId' : ActorMethod<[string, string], undefined>,
  'adminDownloadSubmission' : ActorMethod<[bigint], DownloadResponse>,
  'adminLogin' : ActorMethod<[AdminLoginRequest], AdminLoginResponse>,
  'adminLogout' : ActorMethod<[], undefined>,
  'adminSubmissions' : ActorMethod<[string], Array<ExistingSubmission>>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSubmission' : ActorMethod<
    [string, string, string, ExternalBlob, MediaType],
    undefined
  >,
  'getAllSubmissions' : ActorMethod<[], Array<Submission>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getServerTime' : ActorMethod<[], [] | [Time]>,
  'getSessionRole' : ActorMethod<[], [] | [string]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'listSubmissions' : ActorMethod<[], Array<Submission>>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];