/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const BlobMetadata = IDL.Record({
  'mimeType' : IDL.Text,
  'filename' : IDL.Text,
  'sizeBytes' : IDL.Nat,
});
export const MediaType = IDL.Variant({
  'audio' : IDL.Null,
  'video' : IDL.Null,
});
export const DownloadResponse = IDL.Variant({
  'ok' : IDL.Record({
    'originalFileName' : IDL.Text,
    'data' : ExternalBlob,
    'fileName' : IDL.Text,
    'fileType' : IDL.Text,
  }),
  'forbidden' : IDL.Text,
  'notFound' : IDL.Text,
});
export const ExistingSubmission = IDL.Record({
  'id' : IDL.Nat,
  'studentId' : IDL.Text,
  'assessment' : IDL.Text,
  'mediaType' : MediaType,
  'course' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BackendStatus = IDL.Variant({
  'degraded' : IDL.Null,
  'offline' : IDL.Null,
  'online' : IDL.Null,
});
export const HealthStatus = IDL.Record({
  'backendStatus' : BackendStatus,
  'backendVersion' : IDL.Text,
});
export const Time = IDL.Int;
export const Submission = IDL.Record({
  'id' : IDL.Nat,
  'media' : ExternalBlob,
  'downloadFilename' : IDL.Text,
  'studentId' : IDL.Text,
  'originalFilename' : IDL.Text,
  'assessment' : IDL.Text,
  'metadata' : BlobMetadata,
  'submittedBy' : IDL.Opt(IDL.Principal),
  'mediaType' : MediaType,
  'course' : IDL.Text,
  'submittedAtUtc' : Time,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminCreateSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, BlobMetadata, MediaType],
      [],
      [],
    ),
  'adminDeleteSubmissionById' : IDL.Func([IDL.Nat], [], []),
  'adminDeleteSubmissionByStudentId' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'adminDownloadSubmission' : IDL.Func(
      [IDL.Nat],
      [DownloadResponse],
      ['query'],
    ),
  'adminSubmissions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(ExistingSubmission)],
      ['query'],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkHealth' : IDL.Func([], [HealthStatus], ['query']),
  'createSubmission' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, BlobMetadata, MediaType],
      [],
      [],
    ),
  'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getServerTime' : IDL.Func([], [IDL.Opt(Time)], []),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getVersion' : IDL.Func([], [IDL.Text], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const BlobMetadata = IDL.Record({
    'mimeType' : IDL.Text,
    'filename' : IDL.Text,
    'sizeBytes' : IDL.Nat,
  });
  const MediaType = IDL.Variant({ 'audio' : IDL.Null, 'video' : IDL.Null });
  const DownloadResponse = IDL.Variant({
    'ok' : IDL.Record({
      'originalFileName' : IDL.Text,
      'data' : ExternalBlob,
      'fileName' : IDL.Text,
      'fileType' : IDL.Text,
    }),
    'forbidden' : IDL.Text,
    'notFound' : IDL.Text,
  });
  const ExistingSubmission = IDL.Record({
    'id' : IDL.Nat,
    'studentId' : IDL.Text,
    'assessment' : IDL.Text,
    'mediaType' : MediaType,
    'course' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BackendStatus = IDL.Variant({
    'degraded' : IDL.Null,
    'offline' : IDL.Null,
    'online' : IDL.Null,
  });
  const HealthStatus = IDL.Record({
    'backendStatus' : BackendStatus,
    'backendVersion' : IDL.Text,
  });
  const Time = IDL.Int;
  const Submission = IDL.Record({
    'id' : IDL.Nat,
    'media' : ExternalBlob,
    'downloadFilename' : IDL.Text,
    'studentId' : IDL.Text,
    'originalFilename' : IDL.Text,
    'assessment' : IDL.Text,
    'metadata' : BlobMetadata,
    'submittedBy' : IDL.Opt(IDL.Principal),
    'mediaType' : MediaType,
    'course' : IDL.Text,
    'submittedAtUtc' : Time,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminCreateSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, BlobMetadata, MediaType],
        [],
        [],
      ),
    'adminDeleteSubmissionById' : IDL.Func([IDL.Nat], [], []),
    'adminDeleteSubmissionByStudentId' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'adminDownloadSubmission' : IDL.Func(
        [IDL.Nat],
        [DownloadResponse],
        ['query'],
      ),
    'adminSubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(ExistingSubmission)],
        ['query'],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkHealth' : IDL.Func([], [HealthStatus], ['query']),
    'createSubmission' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, ExternalBlob, BlobMetadata, MediaType],
        [],
        [],
      ),
    'getAllSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getServerTime' : IDL.Func([], [IDL.Opt(Time)], []),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getVersion' : IDL.Func([], [IDL.Text], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listSubmissions' : IDL.Func([], [IDL.Vec(Submission)], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  });
};

export const init = ({ IDL }) => { return []; };