/**
 * TypeScript module declaration for generated declarations/backend package.
 * This allows importing idlFactory and canisterId from the generated declarations.
 * These are generated by dfx generate backend during the build process.
 */
declare module '../../declarations/backend' {
  import type { IDL } from '@dfinity/candid';
  
  export const idlFactory: IDL.InterfaceFactory;
  export const canisterId: string;
}
